services:
  fynn-dev:
    image: fynn-dev:${IMAGE_TAG}
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"

      # Development domain
      - "traefik.http.routers.fynn-dev.rule=Host(`fynn.stacktastik.dev`)"
      - "traefik.http.routers.fynn-dev.entrypoints=websecure"
      - "traefik.http.routers.fynn-dev.tls.certresolver=myresolver"

      # Load balancer port
      - "traefik.http.services.fynn-dev.loadbalancer.server.port=3000"
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
